### ISSUE TITLE
Support for producing TS files when creating a new package

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-package-generator#102]
### Story

- **Given**: I am a user and want to have `.ts` files when creating a new package.
- **When**: I execute the `create-package ...` command.
- **Then**: The tool should ask about the output type that allows choosing between JavaScript (default) and TypeScript.

### Hints

- CKEditor 5, so far, does not have published typings. Hence, we need to use typings produced by the community: `@types/ckeditor__ckeditor5-*`
- We need to figure out how to maintain source files. Do we want a single file that will be aligned based on the target language?
- A TypeScript project might need additional files, e.g., `tsconfig.json`.

**Comment by psmyrek** [comment]
Done in https://github.com/ckeditor/ckeditor5-package-generator/commit/13dd29c0ae11fecfda03a5c793d5ff749bfa2cf1.
