### ISSUE TITLE
Support for building the DLL build from TypeScript

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-package-generator#103]
### Story

- **Given**: I am a user who created a new package.
- **And**: I use TypeScript in the package.
- **When**: I want to build DLL files.
- **Then**: The package generator process `*.ts` files.
- **And**: The compilation process ends without errors.

### Hints

- We need to add the `ts-loader` to [webpack](https://github.com/ckeditor/ckeditor5-package-generator/blob/1110f2ea199025cde79089f25fe6e6d12014cbfa/packages/ckeditor5-package-tools/lib/utils/get-webpack-config-dll.js)].

**Comment by psmyrek** [comment]
Done in #115.
