### ISSUE TITLE
Support for running a manual sample

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-package-generator#105]
### Story

- **Given**: I am a user who created a new package.
- **And**: I use TypeScript in the package.
- **When**: I want to check whether my package behaves correctly.
- **And**: I execute a command for creating a server for displaying a sample.
- **Then**: The environment understands the TypeScript project.
- **And**: The compilation process ends without errors.

### Hints

- We need to add the `ts-loader` to [webpack](https://github.com/ckeditor/ckeditor5-package-generator/blob/1110f2ea199025cde79089f25fe6e6d12014cbfa/packages/ckeditor5-package-tools/lib/utils/get-webpack-config-server.js).

**Comment by przemyslaw-zan** [comment]
Done in #114.
