### ISSUE TITLE
Support for collecting translation entries from TypeScript files

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-package-generator#106]
### Story

- **Given**: I am a user who created a new package.
- **And**: I use TypeScript in the package.
- **When**: I collect translation strings.
- **Then**: The tool produces the `en.po` file which is ready for sending to Transifex.

### Hints

- Basically, we want to make sure whether calls of the `t()` function are collected from `*.ts` files.
- CKEditor 5 must support it too. Hence, we need to verify whether it works.

**Comment by psmyrek** [comment]
Done in #116.
