### ISSUE TITLE
TypeScript version of the generated plugin should reflect CKEditor 5 features

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-package-generator#144]
## Provide a description of the task

During the last TS sync, we agreed that packages produced by the tool should be in-line with official CKEditor 5 packages.

It means we should:

* Create the `augmentation.ts` file. Example content below:
	```ts
	import type { UploadAdapter } from './index';
	
	declare module '@ckeditor/ckeditor5-core' {
		interface PluginsMap {
			[ UploadAdapter.pluginName ]: UploadAdapter;
		}
	}
	```
* Update `index.ts` to import the augmentation file.
	```ts
	import './augmentation';
	```
* Update `tsconfig` to include `DOM.Iterable`
	https://github.com/ckeditor/ckeditor5-package-generator/blob/64bdb5ee66fff628a2fd2abc8a4e435f5e5bbece/packages/ckeditor5-package-generator/lib/templates/ts/tsconfig.json.txt#L3-L5
* Update generated [sample/index.html](https://github.com/ckeditor/ckeditor5-package-generator/blob/master/packages/ckeditor5-package-generator/lib/templates/ts/sample/index.html) to reflect recent changes.

**Comment by pomek** [comment]
Let's mention what the `augmentation.ts` file should contain:

* https://ckeditor.com/docs/ckeditor5/latest/api/module_core_plugincollection-PluginsMap.html
* https://ckeditor.com/docs/ckeditor5/latest/api/module_core_commandcollection-CommandsMap.html

**Comment by Witoso** [comment]
Could we tweak the docs as well? 
Rel: https://github.com/ckeditor/ckeditor5/issues/13929

**Comment by martnpaneq** [comment]
Sure, PR for docs is here: https://github.com/ckeditor/ckeditor5/pull/13935.
