### ISSUE TITLE
Convert the repository to ESM and use the latest `ckeditor5-dev-*`

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-package-generator#192]
## Provide a description of the task

This issue is a continuation of #191.

We want to use the upcoming release ([PR](https://github.com/ckeditor/ckeditor5-dev/pull/1011)) of `ckeditor5-dev-*` packages. Unfortunately, it requires converting packages from this repository to ESM, but it also needs aligned CKEditor 5 code ([PR](https://github.com/ckeditor/ckeditor5/pull/17132)).

### Definition of Done

* Packages located in this repository are marked as ESM.
* The `ckeditor5-dev-*` packages are used in their latest versions.
* CI is green.

**Comment by pomek** [comment]
### Current blockers

* [ ] #191.
* [ ] https://github.com/ckeditor/ckeditor5-dev/pull/1011 released to npm.
* [ ] https://github.com/ckeditor/ckeditor5/pull/17132 released to npm (a nightly is enough to verify results).

**Comment by psmyrek** [comment]
Branch with conversion of this repository to ESM: `ci/3772` (https://github.com/ckeditor/ckeditor5-package-generator/compare/master...ci/3772).

**Comment by pomek** [comment]
We can use CKEditor 5 nightly releases to verify if our changes follow a good path. Unfortunately, we can merge them right after the next CKEditor 5 release, which is not scheduled yet. Hence, let's keep them on a feature branch. We will go back to this topic later.

**Comment by yoyo837** [comment]
I can't successfully execute npm install after cloning `https://github.com/ckeditor/ckeditor5`, it seems to be caused by this isssue, how can I successfully install it?

**Comment by pomek** [comment]
@yoyo837, this repository touches a tool for generating a package for use in CKEditor 5. Is it the correct repository to discuss your case?

**Comment by yoyo837** [comment]
> [@yoyo837](https://github.com/yoyo837), this repository touches a tool for generating a package for use in CKEditor 5. Is it the correct repository to discuss your case?

I found this issue link based on the clues from the npm cli error message on above. The message tells me that `@ckeditor/ckeditor5-package-tools/bin/index.js` cannot use the `require` to call the ESM version of `chalk`.

```
npm error /Users/tanghui/.npm/_cacache/tmp/git-clonejCVTc4/node_modules/@ckeditor/ckeditor5-package-tools/bin/index.js:10
npm error const { red } = require( 'chalk' );
npm error                 ^
npm error
npm error Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/tanghui/.npm/_cacache/tmp/git-clonejCVTc4/node_modules/chalk/source/index.js from /Users/tanghui/.npm/_cacache/tmp/git-clonejCVTc4/node_modules/@ckeditor/ckeditor5-package-tools/bin/index.js not supported.
npm error Instead change the require of /Users/tanghui/.npm/_cacache/tmp/git-clonejCVTc4/node_modules/chalk/source/index.js in /Users/tanghui/.npm/_cacache/tmp/git-clonejCVTc4/node_modules/@ckeditor/ckeditor5-package-tools/bin/index.js to a dynamic import() which is available in all CommonJS modules.
npm error     at Object.<anonymous> (/Users/tanghui/.npm/_cacache/tmp/git-clonejCVTc4/node_modules/@ckeditor/ckeditor5-package-tools/bin/index.js:10:17) {
npm error   code: 'ERR_REQUIRE_ESM'
npm error }
npm error
npm error Node.js v18.20.4
npm error error Command failed with exit code 1.
npm error npm error code 1
npm error npm error path /Users/tanghui/.npm/_cacache/tmp/git-clonejCVTc4
npm error npm error command failed
npm error npm error command sh -c yarn run dll:build && yarn run build:dist
npm error
npm error npm error A complete log of this run can be found in: /Users/tanghui/.npm/_logs/2024-10-24T07_30_04_701Z-debug-0.log

npm error A complete log of this run can be found in: /Users/tanghui/.npm/_logs/2024-10-24T07_29_04_966Z-debug-0.log
```

**Comment by yoyo837** [comment]
I cloned the ckeditor5 main repository and checked out the `v43.2.0` tag, commit https://github.com/ckeditor/ckeditor5/commit/46c386c02f1ad935d5d30cf65eaa782854ee64b3
