### ISSUE TITLE
The sample does not work by default (due to missing license key)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-package-generator#208]
## 📝 Provide detailed reproduction steps (if any)

Create a new package.

Run `yarn start`.

### ✔️ Expected result

The sample should work.

### ❌ Actual result

<img width="1689" alt="Image" src="https://github.com/user-attachments/assets/0025ab1d-16ab-4c48-ac92-e7b44900adb8" />

### ❓ Possible solution

Set `licenseKey = 'GPL'`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Solved, but not released yet.
