### ISSUE TITLE
Add spinner during the installation

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5-package-generator#52]
## 📝 Provide a description of the improvement

When generating the package without `--verbose` option, it takes some time to install the dependencies and do all things that are necessary under the hood. During this time user has no information on what is currently going on. It would be a nice finishing touch to show the user a spinner, to indicate that everything is fine and installation is 'in progress'.

## 📃 Other details

* Node: …
* Npm / Yarn: …
* First affected version: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
It might be also a good idea to add a short disclaimer that installing packages might take a few minutes, so a user will be aware that the script didn't hang up.
