### ISSUE TITLE
The `scripts/ci/travis-check.js` executed on Windows does not remove the tested package

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5-package-generator#79]
## 📝 Provide detailed reproduction steps (if any)

On Windows, call `node scripts/ci/travis-check.js` and wait until all checks are done.

### ✔️ Expected result

The script moves the created package `ckeditor5-test-package` next to the `ckeditor5-package-generator` repository. At the end of all the checks, the tested package `ckeditor5-test-package` should be removed.

### ❌ Actual result

The tested package `ckeditor5-test-package` is not removed.

I don't know if this is the case on other OSes.

## 📃 Other details

* Node: 14.18.1
* Npm / Yarn: 6.14.15 / 1.22.17

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by psmyrek** [comment]
Below are my findings:

- On Windows, for unknown reasons, the `childProcess.kill()` does not terminate successfully the development server processes. This in turn made it impossible to remove the created test package directory, because the `EBUSY` error was emitted when trying to remove it.
- Waiting on the `exit` event from the killed child process did not help and the `EBUSY` error was still emitted.
   - The `close` event was never received so probably this indicates that the child process was not successfully terminated.
- Ignoring (instead of piping) the `stdin` in the spawned child process also did not help.
- Even adding a 20 seconds timeout after receiving the `exit` event from the child process did not help and the `EBUSY` was still emitted when trying to delete the test package directory.
- [Found an interesting issue](https://github.com/webpack/webpack-dev-server/issues/2168) that the `webpack-dev-server` cannot be killed when it was spawned with `child_process` on Windows. Might be the case here.

The workaround I've got for now is to detect the operating system and in case of Windows, call the built-in `taskkill` util instead of the `childProcess.kill()` method on the child process.

**Comment by pomek** [comment]
> The workaround I've got for now is to detect the operating system and in case of Windows, call the built-in taskkill util instead of the childProcess.kill() method on the child process.

Perhaps could we execute the [`kill`](https://www.cyberciti.biz/faq/unix-kill-command-examples/) command on Unix environments too, to unify the solution?

**Comment by psmyrek** [comment]
> > The workaround I've got for now is to detect the operating system and in case of Windows, call the built-in taskkill util instead of the childProcess.kill() method on the child process.
> 
> Perhaps could we execute the [`kill`](https://www.cyberciti.biz/faq/unix-kill-command-examples/) command on Unix environments too, to unify the solution?

Windows contains the `kill` util so in theory we could use the same command on all OSes &mdash; `kill <pid>` &mdash; but on Windows... it does not work. After calling `kill <pid>` I'm always getting `kill: <pid>: No such process`. Using `taskkill /pid <pid>` the given process is always successfully terminated. Maybe this is the reason that the `taskkill` util replaces the old `kill` util, as mentioned [in the Microsoft docs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/taskkill).

**Comment by psmyrek** [comment]
To unify the behavior, as suggested by @pomek, we could use the `taskkill` on Windows and `kill` on other OSes, with appropriate arguments that the given util supports.
