### ISSUE TITLE
Cannot find module 'webpack'

### ISSUE THREAD

**Issue by lauriii** [ckeditor/ckeditor5-package-generator#89]
## 📝 Provide detailed reproduction steps (if any)

1. Ran `yarn add --global ckeditor5-package-generator` to install package
2. Ran `npx ckeditor5-package-generator @drupal/ckeditor5-test` to generate a new plugin

### ✔️ Expected result

Should have generated `@drupal/ckeditor5-test` plugin. 

### ❌ Actual result

Error:
```
$ npx ckeditor5-package-generator @drupal/ckeditor5-test
Cannot find module 'webpack'
Require stack:
- /Users/lauri.eskola/.config/yarn/global/node_modules/@ckeditor/ckeditor5-dev-utils/lib/builds/getdllpluginwebpackconfig.js
- /Users/lauri.eskola/.config/yarn/global/node_modules/@ckeditor/ckeditor5-dev-utils/lib/builds/index.js
- /Users/lauri.eskola/.config/yarn/global/node_modules/@ckeditor/ckeditor5-dev-utils/lib/index.js
- /Users/lauri.eskola/.config/yarn/global/node_modules/ckeditor5-package-generator/lib/index.js
```

## 📃 Other details

* Node: v14.18.1
* Npm / Yarn: Yarn 1.22.17

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
I can reproduce the issue. So far, the `@ckeditor/ckeditor5-dev-utils` package misses the `webpack` dependency. Perhaps defining it in `package.json` should fix the problem.

**Comment by pomek** [comment]
Fix releases in https://github.com/ckeditor/ckeditor5-package-generator/releases/tag/v1.0.0-beta.4.

**Comment by pomek** [comment]
@lauriii, could you verify whether you can reproduce the issue using the latest version of the tool?

**Comment by lauriii** [comment]
This fixes it, thank you 👍
